In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv('DataSet/Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
y, class_names = pd.factorize(df.Species, sort=True)

class_names

Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')

In [6]:
y[45:55]

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

<h3>Keras : to_categorical<h3>

In [16]:
from tensorflow.keras.utils import to_categorical

to_categorical(1, 3).astype(int)

array([0, 1, 0])

In [17]:
cattegories, ids = np.unique(df.Species, return_inverse=True)

In [18]:
cattegories

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [19]:
ids

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
def one_hot_key(arr):
    cattegories, ids = np.unique(arr, return_inverse=True)
    return to_categorical(ids, len(cattegories))

y_1h = one_hot_key(df.Species).astype(int)

y_1h[47:52]

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [21]:
df.iloc[98].Species

'Iris-versicolor'

<h3>Pandas : get_dummies</h3>

In [22]:
y[:5]

array([0, 0, 0, 0, 0])

In [23]:
y_1hgd = pd.get_dummies(y)

In [24]:
y_1hgd[130:135]

0      1     2
130  False  False  True
131  False  False  True
132  False  False  True
133  False  False  True
134  False  False  True

<h3>SKlearn : OneHotEncoder</h3>

In [25]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()

y2 = df.Species.to_numpy()
y2 = y2.reshape(-1, 1)

y2[:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype=object)

In [26]:
y_1hsk = enc.fit_transform(y2).toarray().astype(int)

In [27]:
y_1hsk[14]

array([1, 0, 0])